# Generated by Django 6.0.4 on 2026-04-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bio', models.TextField(blank=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('photo', models.ImageField(upload_to='barbers/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.PositiveSmallIntegerField(help_text='Time in minutes')),
                ('barbers', models.ManyToManyField(related_name='services', to='barber.barber')),
            ],
        ),
    ]
